// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmKRYLpgahcexMt6BiEgoPoSDUKyOyaNg',
    appId: '1:368943120677:web:b17032dcac9ec0db785acc',
    messagingSenderId: '368943120677',
    projectId: 'beta-8acd7',
    authDomain: 'beta-8acd7.firebaseapp.com',
    storageBucket: 'beta-8acd7.appspot.com',
    measurementId: 'G-B87L5PB1MG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUxgiugkR1D9y_6pCSFJGNKslwFaLYXkE',
    appId: '1:368943120677:android:be3f6c0daca19a84785acc',
    messagingSenderId: '368943120677',
    projectId: 'beta-8acd7',
    storageBucket: 'beta-8acd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcb_koQM--FoBvIOSy8ACQ8fmduX-iyX0',
    appId: '1:368943120677:ios:da40eeef3587a7b8785acc',
    messagingSenderId: '368943120677',
    projectId: 'beta-8acd7',
    storageBucket: 'beta-8acd7.appspot.com',
    iosClientId: '368943120677-9fhid3uoth7igon4td60e1op3rhf9pb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcb_koQM--FoBvIOSy8ACQ8fmduX-iyX0',
    appId: '1:368943120677:ios:da40eeef3587a7b8785acc',
    messagingSenderId: '368943120677',
    projectId: 'beta-8acd7',
    storageBucket: 'beta-8acd7.appspot.com',
    iosClientId: '368943120677-9fhid3uoth7igon4td60e1op3rhf9pb4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFlutter',
  );
}
